# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CreateTransaction.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'CreateTransaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x43reateTransaction.proto\"I\n\x15RequestForTransaction\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0f\n\x07id_user\x18\x02 \x01(\x05\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x05\":\n\x18ResponseAboutTransaction\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0e\n\x06report\x18\x02 \x01(\t2P\n\x11\x43reateTransaction\x12;\n\x06\x43reate\x12\x16.RequestForTransaction\x1a\x19.ResponseAboutTransactionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CreateTransaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTFORTRANSACTION']._serialized_start=27
  _globals['_REQUESTFORTRANSACTION']._serialized_end=100
  _globals['_RESPONSEABOUTTRANSACTION']._serialized_start=102
  _globals['_RESPONSEABOUTTRANSACTION']._serialized_end=160
  _globals['_CREATETRANSACTION']._serialized_start=162
  _globals['_CREATETRANSACTION']._serialized_end=242
# @@protoc_insertion_point(module_scope)
