# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Lab2_pb2 as Lab2__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Lab2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SayHelloStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recommed = channel.unary_unary(
                '/SayHello/Recommed',
                request_serializer=Lab2__pb2.HelloRequest.SerializeToString,
                response_deserializer=Lab2__pb2.HelloResponse.FromString,
                _registered_method=True)


class SayHelloServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Recommed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SayHelloServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recommed': grpc.unary_unary_rpc_method_handler(
                    servicer.Recommed,
                    request_deserializer=Lab2__pb2.HelloRequest.FromString,
                    response_serializer=Lab2__pb2.HelloResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SayHello', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SayHello', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SayHello(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Recommed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SayHello/Recommed',
            Lab2__pb2.HelloRequest.SerializeToString,
            Lab2__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
